/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.41
 * Generated at: 2018-02-27 07:18:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class File_005ftest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/datatableLib.jsp", Long.valueOf(1517549725210L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1513593037884L));
    _jspx_dependants.put("jar:file:/D:/PARTH%20DATA/FormGeneratorUtility/FormUtility%20SVN%20WORKSPACE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FormGeneratorUtility/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!-- DATATABLE CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../datatable/css/buttons.dataTables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../datatable/css/editor.dataTables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../datatable/css/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../datatable/css/jquery.dataTables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../datatable/css/select.dataTables.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- DATATABLE JS -->\r\n");
      out.write("<script src=\"../datatable/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"../datatable/js/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"../datatable/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script src=\"../datatable/js/dataTables.buttons.min.js\"></script>\r\n");
      out.write("<script src=\"../datatable/js/dataTables.select.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- JQUERY-VALIDATE -->\r\n");
      out.write("<script src=\"../jquery-validate/jquery.validate.js\"></script>\r\n");
      out.write("<script src=\"../jquery-validate/jquery.validate.min.js\"></script>\r\n");
      out.write("<script src=\"../jquery-validate/additional-methods.js\"></script>\r\n");
      out.write("<script src=\"../jquery-validate/additional-methods.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("</html>");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>File_test</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/jquery.datetimepicker.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/forms.css\">\r\n");
      out.write("<!-- <script src=\"../js/jquery-3.2.1.min.js\"></script> -->\r\n");
      out.write("<script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"../js/jquery.datetimepicker.full.js\"></script>\r\n");
      out.write("<script src=\"../js/formutility.js\"></script>\r\n");
      out.write("<script src=\"../js/custom_alert.js\"></script>\r\n");
      out.write("<script src=\"../js/bootstrap-show-password.min.js\"></script>\r\n");
      out.write("<script src=\"../js/js-form-validator.min.js\"></script>\r\n");
      out.write("<script src=\"../js/jquery.serializejson.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('[data-toggle=\"popover\"]').popover();\r\n");
      out.write("\t\t$('body').tooltip({\r\n");
      out.write("\t\t\tselector : '[rel=tooltip]'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("label[id*=\"-error\"] {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<a href='../index' class='glyphicon glyphicon-home btn-lg'\r\n");
      out.write("\t\tstyle='text-decoration: none; margin: 10px 20px; color: black;'></a>\r\n");
      out.write("\t<a class='glyphicon glyphicon-question-sign btn-lg' href='#'\r\n");
      out.write("\t\ttitle='Help' data-toggle='popover' data-placement='left'\r\n");
      out.write("\t\tdata-trigger='focus' data-content='Testing of file upload'\r\n");
      out.write("\t\tstyle='text-decoration: none; position: absolute; top: 0; right: 0; margin: 10px 20px; color: black;'></a>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t<h2>File_test</h2>\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t\t<form action=\"../insertForm/File_test\" id=\"idFile_test\"\r\n");
      out.write("\t\t\tclass=\"form-horizontal\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label col-sm-4\">Name</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"name\" id=\"name\"\r\n");
      out.write("\t\t\t\t\t\ttabindex=\"1\" maxlength=\"45\" title=\"Name\" rel=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"tooltip\" data-placement=\"right\"\r\n");
      out.write("\t\t\t\t\t\tdata-rule=\"required|Only_aplha\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label col-sm-4\">uuid</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"aadhar\" id=\"aadhar\"\r\n");
      out.write("\t\t\t\t\t\ttabindex=\"2\" title=\"aadhar\" accept=\":accept\" rel=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"tooltip\" data-placement=\"right\"\r\n");
      out.write("\t\t\t\t\t\tonchange=\"checkFile('aadhar')\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label col-sm-4\">pan</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"pan\" id=\"pan\"\r\n");
      out.write("\t\t\t\t\t\ttabindex=\"3\" title=\"pan\" accept=\":accept\" rel=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"tooltip\" data-placement=\"right\"\r\n");
      out.write("\t\t\t\t\t\tonchange=\"checkFile('pan')\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label col-sm-4\">documents</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"documents\"\r\n");
      out.write("\t\t\t\t\t\tid=\"documents\" tabindex=\"4\" title=\"docs\" accept=\":accept\"\r\n");
      out.write("\t\t\t\t\t\trel=\"tooltip\" data-toggle=\"tooltip\" data-placement=\"right\"\r\n");
      out.write("\t\t\t\t\t\tonchange=\"checkFile('documents')\" multiple />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label col-sm-4\">all files</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"all_files\"\r\n");
      out.write("\t\t\t\t\t\tid=\"all_files\" tabindex=\"5\" title=\"images\" accept=\":accept\"\r\n");
      out.write("\t\t\t\t\t\trel=\"tooltip\" data-toggle=\"tooltip\" data-placement=\"right\"\r\n");
      out.write("\t\t\t\t\t\tonchange=\"checkFile('all_files')\" multiple />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-offset-4 col-sm-5\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" class=\"btn btn-success\" id=\"submitFile_test\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"Submit\" /><input type='button' class='btn Info'\r\n");
      out.write("\t\t\t\t\t\tid='search' onclick='loadDataTable()' value='Search' />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<font color='red'><p id=\"errMessage\"></p></font>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\" style=\"overflow-x: auto;\">\r\n");
      out.write("\t\t<table id=\"tableFile_test\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t\t<th>uuid</th>\r\n");
      out.write("\t\t\t\t\t<th>pan</th>\r\n");
      out.write("\t\t\t\t\t<th>documents</th>\r\n");
      out.write("\t\t\t\t\t<th>all files</th>\r\n");
      out.write("\t\t\t\t\t<th>Edit</th>\r\n");
      out.write("\t\t\t\t\t<th>Delete</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t\t<th>uuid</th>\r\n");
      out.write("\t\t\t\t\t<th>pan</th>\r\n");
      out.write("\t\t\t\t\t<th>documents</th>\r\n");
      out.write("\t\t\t\t\t<th>all files</th>\r\n");
      out.write("\t\t\t\t\t<th>Edit</th>\r\n");
      out.write("\t\t\t\t\t<th>Delete</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tfoot>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"dialogFile_test\" style=\"display: none\">\r\n");
      out.write("\t\t<form id=\"dialogformFile_test\" class=\"form-horizontal\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"formOption\" value=\"\"><input\r\n");
      out.write("\t\t\t\ttype=\"hidden\" id=\"ID\" value=\"\">\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label col-sm-4\">Name</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"name\" id=\"df_name\"\r\n");
      out.write("\t\t\t\t\t\ttabindex=\":tabindex\" maxlength=\"45\" title=\"\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label col-sm-4\">uuid</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"aadhar\"\r\n");
      out.write("\t\t\t\t\t\tid=\"df_aadhar\" tabindex=\":tabindex\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\taccept=\"application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label col-sm-4\">pan</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"pan\" id=\"df_pan\"\r\n");
      out.write("\t\t\t\t\t\ttabindex=\":tabindex\" title=\"\" accept=\"application/pdf\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label col-sm-4\">documents</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"documents\"\r\n");
      out.write("\t\t\t\t\t\tid=\"df_documents\" tabindex=\":tabindex\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\taccept=\"application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\"\r\n");
      out.write("\t\t\t\t\t\tmultiple />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label col-sm-4\">all files</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"all_files\"\r\n");
      out.write("\t\t\t\t\t\tid=\"df_all_files\" tabindex=\":tabindex\" title=\"\" accept=\"image/*\"\r\n");
      out.write("\t\t\t\t\t\tmultiple />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"../js/formutility_date.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar returnType = true;\r\n");
      out.write("\tvar errMessage = \"\";\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#submitFile_test')\r\n");
      out.write("\t\t\t\t.click(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tvar control = document.getElementById(\"aadhar\");\r\n");
      out.write("\t\t\t\t\t\t\tvar files = control.files;\r\n");
      out.write("\t\t\t\t\t\t\tif (files.length == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"errMessage\").innerHTML = \"Please select file.\";\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t} else if (errMessage != \"\") {\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"errMessage\").innerHTML = errMessage;\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tvar control = document.getElementById(\"pan\");\r\n");
      out.write("\t\t\t\t\t\t\tvar files = control.files;\r\n");
      out.write("\t\t\t\t\t\t\tif (files.length == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"errMessage\").innerHTML = \"Please select file.\";\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t} else if (errMessage != \"\") {\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"errMessage\").innerHTML = errMessage;\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tvar control = document.getElementById(\"documents\");\r\n");
      out.write("\t\t\t\t\t\t\tvar files = control.files;\r\n");
      out.write("\t\t\t\t\t\t\tif (files.length == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"errMessage\").innerHTML = \"Please select file.\";\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t} else if (errMessage != \"\") {\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"errMessage\").innerHTML = errMessage;\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tvar control = document.getElementById(\"all_files\");\r\n");
      out.write("\t\t\t\t\t\t\tvar files = control.files;\r\n");
      out.write("\t\t\t\t\t\t\tif (files.length == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"errMessage\").innerHTML = \"Please select file.\";\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t} else if (errMessage != \"\") {\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"errMessage\").innerHTML = errMessage;\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"errMessage\").innerHTML = \"\";\r\n");
      out.write("\t\t\t\t\t\t\treturn returnType;\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction checkFile(id) {\r\n");
      out.write("\t\tcheckFileType(id);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\tnew Validator(document.querySelector('#idFile_test'), function(err, res) {\r\n");
      out.write("\t\treturn res;\r\n");
      out.write("\t}, options = {\r\n");
      out.write("\t\trules : {\r\n");
      out.write("\t\t\tOnly_aplha : function(a) {\r\n");
      out.write("\t\t\t\treturn (new RegExp('^[A-Za-z]{0,}$')).test(a)\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tmessages : {\r\n");
      out.write("\t\t\ten : {\r\n");
      out.write("\t\t\t\tOnly_aplha : {\r\n");
      out.write("\t\t\t\t\tempty : \"Only alphabets allow.\",\r\n");
      out.write("\t\t\t\t\tincorrect : \"Only alphabets allow.\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction loadDataTable() {\r\n");
      out.write("\t\tif ($.fn.DataTable.isDataTable('#tableFile_test')) {\r\n");
      out.write("\t\t\t$('#tableFile_test').DataTable().clear().destroy();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar oTable = $('#tableFile_test').dataTable({\r\n");
      out.write("\t\t\t\"dom\" : 'Blfrtip',\r\n");
      out.write("\t\t\t\"buttons\" : [ {\r\n");
      out.write("\t\t\t\ttext : 'Add',\r\n");
      out.write("\t\t\t\taction : function(e, dt, node, config) {\r\n");
      out.write("\t\t\t\t\tvar validator = $('#dialogformFile_test').validate();\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('dialogformFile_test').reset();\r\n");
      out.write("\t\t\t\t\tvalidator.resetForm();\r\n");
      out.write("\t\t\t\t\t$(\"#formOption\").val(\"add\");\r\n");
      out.write("\t\t\t\t\t$('#dialogFile_test').dialog('open');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} ],\r\n");
      out.write("\t\t\t\"columns\" : [ {\r\n");
      out.write("\t\t\t\t\"data\" : \"name\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\t\"data\" : \"aadhar\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\t\"data\" : \"pan\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\t\"data\" : \"documents\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\t\"data\" : \"all_files\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\t\"data\" : \"edit\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\t\"data\" : \"delete\"\r\n");
      out.write("\t\t\t}, ],\r\n");
      out.write("\t\t\t\"columnDefs\" : [ {\r\n");
      out.write("\t\t\t\torderable : false,\r\n");
      out.write("\t\t\t\ttargets : [ -1, -2 ]\r\n");
      out.write("\t\t\t} ],\r\n");
      out.write("\t\t\t\"processing\" : true,\r\n");
      out.write("\t\t\t\"serverSide\" : true,\r\n");
      out.write("\t\t\t\"paging\" : true,\r\n");
      out.write("\t\t\t\"ajax\" : {\r\n");
      out.write("\t\t\t\t\"contentType\" : \"application/json\",\r\n");
      out.write("\t\t\t\t\"data\" : function(d) {\r\n");
      out.write("\t\t\t\t\td.formData = $('#idFile_test').serializeArray();\r\n");
      out.write("\t\t\t\t\treturn JSON.stringify(d);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"url\" : \"../listForDatatable/File_test\",\r\n");
      out.write("\t\t\t\t\"dataSrc\" : \"data\",\r\n");
      out.write("\t\t\t\t\"type\" : \"POST\"\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#tableFile_test_filter input').unbind();\r\n");
      out.write("\t\t$('#tableFile_test_filter input').bind('keyup', function(e) {\r\n");
      out.write("\t\t\tif (e.keyCode == 13) {\r\n");
      out.write("\t\t\t\toTable.fnFilter(this.value);\r\n");
      out.write("\t\t\t} else if (!this.value.trim()) {\r\n");
      out.write("\t\t\t\toTable.fnFilter(this.value);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#tableFile_test tfoot th')\r\n");
      out.write("\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tvar title = $(this).text();\r\n");
      out.write("\t\t\t\t\t\t\tif (!(title.toUpperCase() == ('edit').toUpperCase())\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&& !(title.toUpperCase() == ('delete')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.toUpperCase())) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.html(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'<input type=\"text\" placeholder=\"Search '+title+'\" />');\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\toTable.api().columns().every(function() {\r\n");
      out.write("\t\t\tvar that = this;\r\n");
      out.write("\t\t\t$('input', this.footer()).on('keyup change', function(e) {\r\n");
      out.write("\t\t\t\tif (e.keyCode == 13) {\r\n");
      out.write("\t\t\t\t\tthat.search(this.value).draw();\r\n");
      out.write("\t\t\t\t} else if (!this.value.trim()) { /*fire when search box gets empty */\r\n");
      out.write("\t\t\t\t\tthat.search(this.value).draw();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction editRow(id) {\r\n");
      out.write("\t\tvar validator = $('#dialogformFile_test').validate();\r\n");
      out.write("\t\tdocument.getElementById('dialogformFile_test').reset();\r\n");
      out.write("\t\tvalidator.resetForm();\r\n");
      out.write("\t\t$(\"#ID\").val(\"\");\r\n");
      out.write("\t\t$(\"#formOption\").val(\"edit\");\r\n");
      out.write("\t\tdocument.getElementById(\"errMessage\").innerHTML = \"\";\r\n");
      out.write("\t\t$\r\n");
      out.write("\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\turl : \"../restFatchDataFromID/File_test\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\"id\" : id\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tcache : false,\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tvar jsonData = JSON.parse(result);\r\n");
      out.write("\t\t\t\t\t\tif (jsonData['error']) {\r\n");
      out.write("\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tjsonData['error'],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfunction(key, value) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById(\"errMessage\").innerHTML += \"<font color='red'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ value + \"</font><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tjsonData,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfunction(key, value) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tif (key == 'ID') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\"#ID\").val(value);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tif ($(\"#df_\" + key).is(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t':radio')) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"input[id=df_\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ key\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"][value=\\\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ value\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"\\\"]\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.prop(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'checked',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttrue);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t} else if ($(\"#df_\" + key)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.is(':checkbox')) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (value.indexOf(',') > -1) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar array = value\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.split(',');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfor (var i = 0; i < array.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"input[id=df_\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ key\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"][value=\\\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ array[i]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"\\\"]\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.prop(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'checked',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttrue);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"input[id=df_\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ key\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"][value=\\\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ value\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"\\\"]\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.prop(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'checked',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttrue);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t} else if ($(\"#df_\" + key)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.is(':file')) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\"#df_\" + key).val(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t$('#dialogFile_test').dialog('open');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(XMLHttpRequest, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"errMessage\").innerHTML = \"<font color='red'>Problem in fatching data.</font>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction deleteRow(id) {\r\n");
      out.write("\t\tvar value = confirm(\"Are you sure want to delete this record?\");\r\n");
      out.write("\t\tif (value == true) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"errMessage\").innerHTML = \"\";\r\n");
      out.write("\t\t\t$\r\n");
      out.write("\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\turl : \"../delete/File_test\",\r\n");
      out.write("\t\t\t\t\t\tdata : \"{\\\"ID\\\":\" + id + \"}\",\r\n");
      out.write("\t\t\t\t\t\tcontentType : \"application/json; charset=utf-8\",\r\n");
      out.write("\t\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\t\tcache : false,\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t\tif (result['error']) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tresult['error'],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfunction(key, value) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById(\"errMessage\").innerHTML += \"<font color='red'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ value\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</font><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t} else if (result['success']) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tresult['success'],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfunction(key, value) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById(\"errMessage\").innerHTML += \"<font color='green'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ value\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</font><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\toTable.api().rows().remove().draw();\r\n");
      out.write("\t\t\t\t\t\t\t\toTable.api().draw();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror : function(XMLHttpRequest, textStatus,\r\n");
      out.write("\t\t\t\t\t\t\t\terrorThrown) {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"errMessage\").innerHTML = \"<font color='red'>Record deletion failed.</font>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}); /*$('#tableFile_test').DataTable().draw(); */\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction downloadFile(names) {\r\n");
      out.write("\t\tvar val = confirm(\"Do you want to download file/files?\");\r\n");
      out.write("\t\tif (val == true) {\r\n");
      out.write("\t\t\tvar name = names.split(\"|\");\r\n");
      out.write("\t\t\tfor (var i = 0; i < name.length; i++) {\r\n");
      out.write("\t\t\t\tdownload(name[i]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar oTable = $('#tableFile_test').dataTable({\r\n");
      out.write("\t\t\"dom\" : 'Blfrtip',\r\n");
      out.write("\t\t\"buttons\" : [ {\r\n");
      out.write("\t\t\ttext : 'Add',\r\n");
      out.write("\t\t\taction : function(e, dt, node, config) {\r\n");
      out.write("\t\t\t\tvar validator = $('#dialogformFile_test').validate();\r\n");
      out.write("\t\t\t\tdocument.getElementById('dialogformFile_test').reset();\r\n");
      out.write("\t\t\t\tvalidator.resetForm();\r\n");
      out.write("\t\t\t\t$(\"#formOption\").val(\"add\");\r\n");
      out.write("\t\t\t\t$('#dialogFile_test').dialog('open');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} ],\r\n");
      out.write("\t\t\"columns\" : [ {\r\n");
      out.write("\t\t\t\"data\" : \"name\"\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\t\"data\" : \"aadhar\"\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\t\"data\" : \"pan\"\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\t\"data\" : \"documents\"\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\t\"data\" : \"all_files\"\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\t\"data\" : \"edit\"\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\t\"data\" : \"delete\"\r\n");
      out.write("\t\t}, ],\r\n");
      out.write("\t\t\"columnDefs\" : [ {\r\n");
      out.write("\t\t\torderable : false,\r\n");
      out.write("\t\t\ttargets : [ -1, -2 ]\r\n");
      out.write("\t\t} ],\r\n");
      out.write("\t\t\"processing\" : true,\r\n");
      out.write("\t\t\"serverSide\" : false,\r\n");
      out.write("\t\t\"paging\" : true,\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#dialogFile_test')\r\n");
      out.write("\t\t\t\t.dialog(\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tautoOpen : false,\r\n");
      out.write("\t\t\t\t\t\t\ttitle : 'File_test',\r\n");
      out.write("\t\t\t\t\t\t\theight : 500,\r\n");
      out.write("\t\t\t\t\t\t\twidth : 550,\r\n");
      out.write("\t\t\t\t\t\t\tbuttons : {\r\n");
      out.write("\t\t\t\t\t\t\t\t'Send' : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif ($('#dialogformFile_test').valid()) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar formData = new FormData(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$('#dialogformFile_test')[0]);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar ajaxUrl = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar jsonData = JSON.stringify($(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'#dialogformFile_test')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t.serializeJSON());\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif ($(\"#formOption\").val() == \"add\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tajaxUrl = \"../insertWithFile/File_test\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t} else if ($(\"#formOption\").val() == \"edit\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tajaxUrl = \"../updateWithFile/File_test\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tformData.append(\"ID\", $(\"#ID\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.val());\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tjsonData = jsonData.substring(0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tjsonData.length - 1)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+ \",\\\"ID\\\":\\\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+ $(\"#ID\").val() + \"\\\"}\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tajaxUrl = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$('#dialogFile_test').dialog('close');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\turl : ajaxUrl,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata : formData,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcontentType : \"application/json; charset=utf-8\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcache : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tenctype : 'multipart/form-data',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tprocessData : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcontentType : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (result['error']) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tconsole\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.log(result['error']);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult['error'],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tkey,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tconsole\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.log(value);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById(\"errMessage\").innerHTML = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById(\"errMessage\").innerHTML += \"<font color='red'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ value\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</font><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t} else if (result['success']) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tconsole\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.log(result['success']);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult['success'],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tkey,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tconsole\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.log(value);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById(\"errMessage\").innerHTML = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById(\"errMessage\").innerHTML += \"<font color='green'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ value\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</font><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}); /*$('#tableFile_test').DataTable().draw();*//*oTable.ajax.reload();*/\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toTable.api().rows()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.remove()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.draw();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toTable.api().rows\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.add(result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toTable.api().draw();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\terror : function(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tXMLHttpRequest,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttextStatus,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\terrorThrown) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tif ($(\"#formOption\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val() == \"add\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById(\"errMessage\").innerHTML = \"<font color='red'>Record insertion failed.</font>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t} else if ($(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#formOption\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val() == \"edit\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById(\"errMessage\").innerHTML = \"<font color='red'>Record updation failed.</font>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t$('#dialogformFile_test')\r\n");
      out.write("\t\t\t\t.validate(\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\trules : {\r\n");
      out.write("\t\t\t\t\t\t\t\tname : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tpattern : /^[A-Za-z]{0,}$/\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\taadhar : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\taccept : \"application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfilesize : 1048576,\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tpan : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\taccept : \"application/pdf\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfilesize : 1048576,\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tdocuments : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\taccept : \"application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfilesize : 1048576,\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tall_files : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\taccept : \"image/*\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfilesize : 1048576,\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tmessages : {\r\n");
      out.write("\t\t\t\t\t\t\t\tdf_name : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tpattern : \"Only alphabets allow.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /File_test.jsp(98,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty message}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<font color='green'>");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("</font>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fif_005f0_reused) {
        _jspx_th_c_005fif_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /File_test.jsp(99,23) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fout_005f0_reused) {
        _jspx_th_c_005fout_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fout_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /File_test.jsp(101,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty errMessage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<font color='red'> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errMessage }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" </font>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      if (!_jspx_th_c_005fif_005f1_reused) {
        _jspx_th_c_005fif_005f1.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f1);
      }
    }
    return false;
  }
}
